name: tisane
description: Tisane is a decentralized, offline-first Data Mesh integration layer for Flutter, enabling secure FFI communication and conflict-free data synchronization.
version: 1.1.2
homepage: https://github.com/dooapps/tisane
repository: https://github.com/dooapps/tisane

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  infusion_ffi: ^1.3.20
  base64: ^1.0.0
  uuid: ^4.5.1
  mutex: ^3.0.0
  web_socket_channel: ^3.0.3
  webcrypto: ^0.5.3
  convert: ^3.1.1
  path: ^1.9.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_secure_storage: ^9.2.4
  dio: ^5.4.0
  crypto: ^3.0.6
  xxh3: ^1.2.0
  meta: ^1.16.0

dev_dependencies:
  test: ^1.24.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
